# Generated by Django 2.2.2 on 2019-06-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='caption',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='blog',
            name='bodytext',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pubdate',
            field=models.DateTimeField(),
        ),
    ]
